# Generated by Django 4.1.7 on 2023-09-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_products_created_products_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
