# Generated by Django 4.1.7 on 2023-10-08 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_rename_products_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.ImageField(default=1, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderApp.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'line order',
                'verbose_name_plural': 'lines orders',
                'db_table': 'lineorder',
                'ordering': ['id'],
            },
        ),
    ]
